name: 'monkeytype stats'
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  update-readme:
    name: update readme
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: vnphanquang/monkeytype-readme@main
        with:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'time'
          mode2: '30'
          style: 'flat'
          logoVariant: 'one'
          label: 'monkeytype'
